services:
  autowats-cgi-server:
    build: .
    container_name: autowats-cgi-server
    ports:
      - "127.0.0.1:1486:1486"
    restart: unless-stopped
    networks:
      - cgi_network

networks:
  cgi_network:
    driver: bridge
