services:
  autowats-cgi-server:
    build: .
    container_name: autowats-cgi-server
    ports:
      - "127.0.0.1:1486:1486"
    volumes:
      - autowats_db:/var/www/db  # Mount database volume
    restart: unless-stopped
    networks:
      - cgi_network

networks:
  cgi_network:
    driver: bridge

volumes:
  autowats_db:  # Define a named volume
